build(itest): Downgrade jest-playwright-preset to 1.7.0
With 1.7.2 we experienced issues while running tests:

```
TypeError: Cannot read properties of undefined (reading 'resetContextPerTest')
  at Object.<anonymous> (../node_modules/.pnpm/jest-playwright-preset@1.7.2_l32tkdczjgqxuqrrxonq2y4q5e/node_modules/jest-playwright-preset/lib/extends.js:86:53)
```

Further research required prior to upgrading `jest-playwright-preset`.

Downgrading makes the tests run again.