chore(third-party): Roll back xml-formatter to 2.6.1
I failed updating to xml-formatter 3.x. Naive approach
failed in application with:

```
TypeError: (0 , xml_formatter_1.default) is not a function
```

As the main aspect is currently updating CKEditor to 37.x,
reverting the update for now.