chore: Update esbuild-loader
esbuild-loader ... 3.0.1 ❯ 3.2.0

Skipped update to 4.x for now, as this introduces a breaking change
regarding tsconfig-parsing, which makes the existing build of the
example app break.

For 4.2.0 (latest) we get a bunch of error messages, similar to:

```
Error: [esbuild-loader] The specified tsconfig at
  "[...]/app/tsconfig.json" was applied to the file
  "[...]/packages/ckeditor5-common/src/AdvancedTypes.ts" but does not
  match its "include" patterns
    at Object.ESBuildLoader
      ([...]/node_modules/.pnpm/esbuild-loader@4.0.2_webpack@[...])
 @ ../packages/ckeditor5-coremedia-content-clipboard/src/ContentClipboard.ts 35:0-70 43:38-43
 @ ../packages/ckeditor5-coremedia-content-clipboard/src/index.ts 2:0-65 2:0-65
 @ ./src/ckeditor.ts 42:0-84 130:4-20
```